export const DEFAULT_COMMITTEES = [
  // اللجنة العلمية - Scientific Committee
  {
    _id: "scientific-1",
    name: { en: "Dr. Kafah Al-Souri", ar: "الدكتورة كفاح الصوري" },
    committee: "scientific" as const,
    title: { en: "Committee Chair", ar: "رئيس اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 1,
  },
  {
    _id: "scientific-2",
    name: { en: "Prof. Hayel Dawood", ar: "معالي الأستاذ الدكتور هايل داود" },
    committee: "scientific" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "University of Jordan", ar: "الجامعة الأردنية" },
    order: 2,
  },
  {
    _id: "scientific-3",
    name: {
      en: "Prof. Abdulnasser Abu Al-Basal",
      ar: "معالي الأستاذ الدكتور عبدالناصر أبو البصل",
    },
    committee: "scientific" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "University of Jordan", ar: "الجامعة الأردنية" },
    order: 3,
  },
  {
    _id: "scientific-4",
    name: { en: "Prof. Ismail Shindi", ar: "الأستاذ الدكتور اسماعيل شندي" },
    committee: "scientific" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: {
      en: "Palestine Technical University - Kadoorie",
      ar: "جامعة فلسطين التقنية- خضوري/ فلسطين",
    },
    order: 4,
  },
  {
    _id: "scientific-5",
    name: { en: "Prof. Jamil Al-Rifai", ar: "الأستاذ الدكتور جميل الرفاعي" },
    committee: "scientific" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "University of Jordan", ar: "الجامعة الأردنية" },
    order: 5,
  },
  {
    _id: "scientific-6",
    name: {
      en: "Prof. Khaled Abu Sha'ira",
      ar: "الأستاذ الدكتور خالد أبوشعيرة",
    },
    committee: "scientific" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 6,
  },
  {
    _id: "scientific-7",
    name: { en: "Prof. Mohammed Talafeha", ar: "الأستاذ الدكتور محمد طلافحة" },
    committee: "scientific" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Yarmouk University", ar: "جامعة اليرموك" },
    order: 7,
  },
  {
    _id: "scientific-8",
    name: { en: "Dr. Alaa Al-Bourini", ar: "الدكتورة الآء البوريني" },
    committee: "scientific" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 8,
  },
  {
    _id: "scientific-9",
    name: { en: "Dr. Fatima Kassab", ar: "الدكتورة فاطمة كساب" },
    committee: "scientific" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 9,
  },
  {
    _id: "scientific-10",
    name: { en: "Dr. Fajer Qutaishat", ar: "الدكتورة فجر قطيشات" },
    committee: "scientific" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 10,
  },
  {
    _id: "scientific-11",
    name: { en: "Duaa Al-Zoubi", ar: "الأستاذة دعاء الزعبي" },
    committee: "scientific" as const,
    title: { en: "Committee Secretary", ar: "مقرر اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 11,
  },

  // اللجنة التحضيرية - Preparatory Committee
  {
    _id: "preparatory-1",
    name: { en: "Prof. Hassan Al-Zoubi", ar: "الأستاذ الدكتور حسن الزعبي" },
    committee: "preparatory" as const,
    title: { en: "Committee Chair", ar: "رئيس اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 1,
  },
  {
    _id: "preparatory-2",
    name: { en: "Dr. Hajer Al-Akour", ar: "الدكتورة هاجر العكور" },
    committee: "preparatory" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 2,
  },
  {
    _id: "preparatory-3",
    name: { en: "Dr. Abeer Al-Tarawna", ar: "الدكتورة عبير الطراونة" },
    committee: "preparatory" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 3,
  },
  {
    _id: "preparatory-4",
    name: { en: "Dr. Afaf Adinat", ar: "الدكتورة عفاف عدينات" },
    committee: "preparatory" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 4,
  },
  {
    _id: "preparatory-5",
    name: { en: "Dr. Nasiba Al-Mousa", ar: "الدكتورة نسيبة الموسى" },
    committee: "preparatory" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 5,
  },
  {
    _id: "preparatory-6",
    name: { en: "Dr. Al-Muntaser Qaddoura", ar: "الدكتور المنتصر قدورة" },
    committee: "preparatory" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 6,
  },
  {
    _id: "preparatory-7",
    name: { en: "Dr. Lina Al-Jarrah", ar: "الدكتورة لينا الجراح" },
    committee: "preparatory" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 7,
  },
  {
    _id: "preparatory-8",
    name: { en: "Dr. Bilal Abu Aisha", ar: "الدكتور بلال أبوعيشة" },
    committee: "preparatory" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 8,
  },
  {
    _id: "preparatory-9",
    name: { en: "Dr. Sally Al-Shoura", ar: "الدكتورة سالي الشورة" },
    committee: "preparatory" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 9,
  },
  {
    _id: "preparatory-10",
    name: { en: "Mariam Al-Ghamri", ar: "الأستاذة مريم الغمري" },
    committee: "preparatory" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 10,
  },
  {
    _id: "preparatory-11",
    name: { en: "Nour Al-Jarrah", ar: "الأستاذة نور الجراح" },
    committee: "preparatory" as const,
    title: { en: "Committee Secretary", ar: "مقرر اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 11,
  },

  // اللجنة الإعلامية - Media Committee
  {
    _id: "media-1",
    name: { en: "Prof. Ahmad Al-Sheiha", ar: "الأستاذ الدكتور أحمد الشيحة" },
    committee: "media" as const,
    title: { en: "Committee Chair", ar: "رئيس اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 1,
  },
  {
    _id: "media-2",
    name: { en: "Dr. Bilal Abu Quddum", ar: "الدكتور بلال أبوقدوم" },
    committee: "media" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 2,
  },
  {
    _id: "media-3",
    name: { en: "Prof. Suhaila Banat", ar: "الأستاذة الدكتورة سهيلة بنات" },
    committee: "media" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 3,
  },
  {
    _id: "media-4",
    name: { en: "Dr. Kamal Alyan", ar: "الدكتور كمال عليان" },
    committee: "media" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 4,
  },
  {
    _id: "media-5",
    name: { en: "Dr. Faiza Al-Sukar", ar: "الدكتورة فايزة السكر" },
    committee: "media" as const,
    title: {
      en: "Deputy President of Jordan Scholars Association",
      ar: "نائب رئيس رابطة علماء الأردن",
    },
    affiliation: {
      en: "Jordan Scholars Association",
      ar: "رابطة علماء الأردن",
    },
    order: 5,
  },

  // اللجنة التقنية - Technical Committee
  {
    _id: "technical-1",
    name: { en: "Dr. Mohammed Shehab", ar: "الدكتور محمد شهاب" },
    committee: "technical" as const,
    title: { en: "Committee Chair", ar: "رئيس اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 1,
  },
  {
    _id: "technical-2",
    name: { en: "Fayez Abu Hajar", ar: "الأستاذ فايز أبوحجر" },
    committee: "technical" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 2,
  },
  {
    _id: "technical-3",
    name: { en: "Ahmad Al-Mahmoud", ar: "الأستاذ أحمد المحمود" },
    committee: "technical" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 3,
  },
  {
    _id: "technical-4",
    name: { en: "Maria Al-Shishani", ar: "الأستاذة ماريا الشيشاني" },
    committee: "technical" as const,
    title: { en: "Committee Member", ar: "عضو اللجنة" },
    affiliation: { en: "Amman Arab University", ar: "جامعة عمان العربية" },
    order: 4,
  },
];
